wip

diff --git a/pi b/pi
--- a/pi
+++ b/pi
@@ -5,7 +5,7 @@
 fancy_echo() {
   local msg="$1"; shift
 
-  # shellcheck disable=SC2059
+  shellcheck disable=SC2059
   printf "\n**\n" "$@"
   printf "** $msg" "$@"
   printf "\n**\n\n" "$@"
@@ -37,28 +37,40 @@ apt_install() {
   sudo apt install -y $package
 }
 
-# shellcheck disable=SC2154
-#trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+shellcheck disable=SC2154
 
-#set -e
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+set -e
 
 fancy_echo "Update Apt Cache"
 sudo apt update
 
-fancy_echo "Distro Upgrade"
+fancy_echo "Upgrade Installed Packages"
+sudo apt upgrade
+
+fancy_echo "Upgrade Distro"
 sudo apt dist-upgrade
 
 apt_install build-essential
+apt_install gcc
 apt_install zsh
 apt_install git
 apt_install htop
 apt_install hub
+apt_install openssh-server
 apt_install openssl
 apt_install libssl-dev
 apt_install zlib1g-dev
 apt_install tmux
 apt_install vim
 apt_install docker.io
+
+sudo systemctl enable ssh
+sudo systemctl start ssh
+
+sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
+sudo iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
+sudo iptables-save
 
 if [ ! -d "$HOME/.bin/" ]; then mkdir "$HOME/.bin"; fi
 if [ ! -f "$HOME/.zshrc" ]; then touch "$HOME/.zshrc"; fi
